routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('projects/{project}/users', 'TeamController@edit')->name('projects.users.edit');
Route::put('projects/{project}/users', 'TeamController@update')->name('projects.users.update');
Route::put('tasks/{task}/status/{status}', 'TaskController@updateStatus');

Route::resource('projects', 'ProjectController')->except('show');
Route::resource('projects.sprints', 'SprintController');
Route::resource('projects.sprints.tasks', 'TaskController');
Route::resource('projects.sprints.tasks.activities', 'ActivityController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Project
 * @package App
 */
class Project extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description', 'status'];

    /**
     * Get the sprints for the project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sprints()
    {
        return $this->hasMany('App\Sprint');
    }

    /**
     * The Users that belong to the project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany('App\User')->withTimestamps();
    }

    /**
     * Check if the user is a team member of the project
     *
     * @param int $user_id
     * @return bool
     */
    public function user(int $user_id)
    {
        return $this->users()->where('user_id', $user_id)->exists();
    }

    /**
     * Check if the sprint is a sprint of the project
     *
     * @param int $sprint_id
     * @return bool
     */
    public function sprint(int $sprint_id)
    {
        return $this->sprints()->where('id', $sprint_id)->exists();
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Project;
use App\Repositories\ProjectRepository;

/**
 * Class ProjectController
 * @package App\Http\Controllers
 */
class ProjectController extends Controller
{
    /**
     * @var ProjectRepository
     */
    protected $projectRepository;

    /**
     * ProjectController constructor.
     * @param ProjectRepository $projectRepository
     */
    public function __construct(ProjectRepository $projectRepository)
    {
        $this->middleware('auth');
        $this->middleware('admin', ['only' => ['store', 'create', 'update', 'edit', 'destroy']]);
        $this->projectRepository = $projectRepository;
    }

    /**
     * Display a listing of projects using pagination system.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $projects = $this->projectRepository->paginate();
        $pages = $projects->render();
        return view('projects.index', compact('projects', 'pages'));
    }

    /**
     * Show the form for creating a new project.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created project in storage.
     *
     * @param StoreProjectRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreProjectRequest $request)
    {
        $this->projectRepository->store($request->all());
        return redirect()->route('projects.index')->with('success', __('project.success.store'));
    }

    /**
     * Show the form for editing the specified project.
     *
     * @param Project $project
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Project $project)
    {
        return view('projects.edit', compact('project'));
    }

    /**
     * Update the specified project in storage.
     *
     * @param UpdateProjectRequest $request
     * @param int $projectId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateProjectRequest $request, int $projectId)
    {
        $this->projectRepository->update($projectId, $request->all());
        return redirect()->route('projects.index')->with('success', __('project.success.update'));
    }

    /**
     * Remove the specified project from storage.
     *
     * @param int $projectId
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $projectId)
    {
        $this->projectRepository->destroy($projectId);
        return back()->with('success', __('project.success.destroy'));
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('title')
    Projects
@endsection

@section('content')
    @foreach ($errors->all() as $error)
        <span class="alert hide" role="alert">{{ $error }}</span>
    @endforeach
    <div class="card card-form">
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">{{ __('project.title.create') }}<i class="material-icons right">help_outline</i></span>
            {{ Form::open(['route' => 'projects.store']) }}
                <div class="row">
                    <div class="input-field col s12 m6">
                        {{ Form::label('name', __('project.form.label.name')) }}
                        {{ Form::text('name', null, ['data-length' => '60']) }}
                    </div>
                    <div class="input-field col s12 m6">
                        {{ Form::select('status', ['New' => 'New', 'In Progress' => 'In Progress', 'Done' => 'Done'], 'New') }}
                        {{ Form::label('status', __('project.form.label.status')) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ Form::label('description', __('project.form.label.description')) }}
                        {{ Form::textarea('description', null, ['data-length' => '600', 'class' => 'materialize-textarea']) }}

                    </div>
                </div>
                <div class="row">
                    <div class="col right">
                        {{ Form::button(__('project.form.submit.create', ['icon' => '<i class="material-icons right">add</i>']), ['type' => 'submit', 'class' => 'btn waves-effect btn teal lighten-1 hoverable']) }}
                    </div>
                </div>
            {{ Form::close() }}
        </div>
        <!-- TODO: reveal add information -->
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">{{ __('project.title.create') }}<i class="material-icons right">close</i></span>
            <p>{{ __('project.form.help') }}</p>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const alertElems = document.querySelectorAll("span.alert");
            alertElems.forEach(function(e){
                M.toast({ html: e.innerHTML, classes: 'red darken-1', displayLength: 5000 });
            });

            const inputElems = document.querySelectorAll("input[name='name'], textarea[name='description']");
            M.CharacterCounter.init(inputElems);
        });
    </script>
@endpush

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('title')
    Projects
@endsection

@section('content')
    @foreach ($errors->all() as $error)
        <p>tes</p>
        <span class="alert hide" role="alert">{{ $error }}</span>
    @endforeach
    <div class="card card-form">
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">{{ __('project.title.edit', ['project' => $project->name ]) }}<i class="material-icons right">help_outline</i></span>
            {{ Form::open(['route' => ['projects.update', $project->id ], 'method' => 'put']) }}
            <div class="row">
                <div class="input-field col s12 m6">
                    {{ Form::label('name', __('project.form.label.name')) }}
                    {{ Form::text('name', $project->name, ['data-length' => '60']) }}
                </div>
                <div class="input-field col s12 m6">
                    {{ Form::select('status', ['New' => 'New', 'In Progress' => 'In Progress', 'Done' => 'Done'], (string) $project->status) }}
                    {{ Form::label('status', __('project.form.label.status')) }}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ Form::label('description', __('project.form.label.description')) }}
                    {{ Form::textarea('description', $project->description, ['data-length' => '600', 'class' => 'materialize-textarea']) }}

                </div>
            </div>
            <div class="row">
                <div class="col right">
                    {{ Form::button(__('project.form.submit.edit', ['icon' => '<i class="material-icons right">mode_edit</i>']), ['type' => 'submit', 'class' => 'btn waves-effect btn teal lighten-1 hoverable']) }}
                </div>
            </div>
            {{ Form::close() }}
        </div>
        <!-- TODO: reveal add information -->
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">{{ __('project.title.edit', ['project' => $project->name ]) }}<i class="material-icons right">close</i></span>
            <p>{{ __('project.form.help') }}</p>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const alertElems = document.querySelectorAll("span.alert");
            alertElems.forEach(function(e){
                M.toast({ html: e.innerHTML, classes: 'red darken-1', displayLength: 5000 });
            });

            const inputElems = document.querySelectorAll("input[name='name'], textarea[name='description']");
            M.CharacterCounter.init(inputElems);
        });
    </script>
@endpush

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('title')
    Projects
@endsection

@section('content')
    <!-- TODO: use dataTables -->
    <div class="d-flex justify-content-center" aria-label="pagination">
        {{ $pages }}
    </div>

    <table class="highlight responsive-table" id="table-projects">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ __('project.index.table.name') }}</th>
                <th>{{ __('project.index.table.status') }}</th>
                <th class="center">{{ __('project.index.table.sprint') }}</th>
                <th class="center">{{ __('project.index.table.spent_hours') }}</th>
                @if(auth()->user()->is_admin)
                    <th class="center-align">{{ __('project.index.table.action') }}</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($projects as $project)
                <tr>
                    <td>{{ $loop-> index + 1 }}</td>
                    <td><a href="{{ route('projects.sprints.show', [$project->id, $project->sprints->last()]) }}">{{ $project->name }}</a></td>
                    <td>{{ $project->status }}</td>
                    <td class="center">{{ $project->sprints->last()->number }}</td>
                    <td class="center"></td>
                    @if(auth()->user()->is_admin)
                        <td class="center-align">
                            <!-- Modal Trigger -->
                            <button data-target="modal-confirmation-{{ $loop->index + 1 }}" class="waves-effect btn teal lighten-1 modal-trigger" data-toggle="modal">
                                <i class="material-icons">delete_forever</i>
                            </button>
                            <form method="post" action="{{ route('projects.destroy', $project->id) }}" class="hide" id="project-delete-{{ $loop->index + 1 }}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                            <a class="waves-effect btn teal lighten-1" href="{{ route('projects.edit', $project) }}">
                                <i class="material-icons">mode_edit</i>
                            </a>
                            <a class="waves-effect btn teal lighten-1" href="{{ route('projects.users.edit', $project) }}">
                                <i class="material-icons">group_add</i>
                            </a>
                        </td>
                    @endif
                </tr>
                <!-- TODO: use just one modal -->
                <!-- Modal Structure -->
                <div id="modal-confirmation-{{ $loop->index + 1 }}" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-content">
                        <p>{{ __('project.index.destroy_confirmation') }}</p>
                    </div>
                    <div class="modal-footer">
                        <button class="waves-effect waves-green btn green" onclick="event.preventDefault(); document.getElementById('project-delete-{{ $loop->index + 1 }}').submit();">
                            <i class="material-icons">check</i>
                        </button>
                        <button class="modal-close waves-effect waves-green btn red darken-1" data-dismiss="modal">
                            <i class="material-icons">clear</i>
                        </button>
                    </div>
                </div>
            @endforeach
        </tbody>
    </table>

    <div class="d-flex justify-content-center" aria-label="pagination">
        {{ $pages }}
    </div>

    @if(auth()->user()->is_admin)
        <div class="fixed-action-btn">
            <a href="{{ route('projects.create') }}" class="btn-floating waves-effect btn-large teal lighten-1">
                <i class="large material-icons">add</i>
            </a>
        </div>
    @endif
@endsection