routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('projects/{project}/users', 'TeamController@edit')->name('projects.users.edit');
Route::put('projects/{project}/users', 'TeamController@update')->name('projects.users.update');
Route::put('tasks/{task}/status/{status}', 'TaskController@updateStatus');

Route::resource('projects', 'ProjectController')->except('show');
Route::resource('projects.sprints', 'SprintController');
Route::resource('projects.sprints.tasks', 'TaskController');
Route::resource('projects.sprints.tasks.activities', 'ActivityController');

app/Sprint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Sprint
 * @package App
 */
class Sprint extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['project_id', 'number'];

    /**
     * Get the project record associated with the sprint
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo*
     */
    public function project()
    {
        return $this->belongsTo('App\Project');
    }

    /**
     * Get the tasks for the sprint.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tasks()
    {
        return $this->hasMany('App\Task');
    }

    public function tasksByStatus(String $status)
    {
        return $this->tasks->where('status', $status);
    }


}

app/Http/Controllers/SprintController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSprintRequest;
use App\Http\Requests\UpdateSprintRequest;
use App\Repositories\SprintRepository;
use App\Sprint;
use App\Project;

/**
 * Class SprintController
 * @package App\Http\Controllers
 */
class SprintController extends Controller
{
    /**
     * @var SprintRepository
     */
    protected $sprintRepository;

    /**
     * @var int
     */
    protected $paginate = 10;

    /**
     * @var array
     */
    protected $status = [
        'Backlog',
        'In progress',
        'Testing',
        'Ready for review',
        'Done'
    ];

    /**
     * SprintController constructor.
     * @param SprintRepository $sprintRepository
     */
    public function __construct(SprintRepository $sprintRepository)
    {
        $this->middleware('auth');
        $this->middleware('admin', ['only' => 'destroy']);
        $this->middleware('team', ['only' => 'show']);
        $this->sprintRepository = $sprintRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param  \App\Project $project
     * @return \Illuminate\Http\Response
     */
    public function index(Project $project)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Project $project
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Project $project)
    {
        return view('sprints.create', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreSprintRequest $request
     * @param  \App\Project $project
     */
    public function store(StoreSprintRequest $request, Project $project)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project $project
     * @param  \App\Sprint $sprint
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project, Sprint $sprint)
    {
        if ($project->sprint($sprint->id)) {
            $tasksByStatus = collect();
            foreach ($this->status as $s) {
                $tasksByStatus->put($s, $sprint->tasksByStatus($s));
            }
            return view('sprints.show', compact('project', 'sprint', 'tasksByStatus'));
        }
        return back()->with('warning', __('sprint.warning.show'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project $project
     * @param  \App\Sprint $sprint
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project, Sprint $sprint)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateSprintRequest $request
     * @param  \App\Project $project
     * @param  \App\Sprint $sprint
     */
    public function update(UpdateSprintRequest $request, Project $project, Sprint $sprint)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $sprintId
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $sprintId)
    {
        $this->sprintRepository->destroy($sprintId);
        return back()->with('success', __('sprint.success.destroy'));
    }
}

resources/views/sprints/show.blade.php
@extends('layouts.app')

@section('title')
    Projects
@endsection

@section('content')
    <div class="input-field">
        <select data-id="{{ $project->id }}" id="sprint">
            <option value="" disabled>Choose your sprint</option>
            @foreach ($project->sprints as $s)
                <option value="{{ $s->id }}" @if ($sprint->id === $s->id) selected @endif >Sprint {{ $s->number }}</option>
            @endforeach
        </select>
        <label for="sprint">Choose your sprint</label>
    </div>
    <div class="scrumboard">
        <div class="d-flex">
            <!-- TODO: we want to administrate the scrum board list -->
            @foreach($tasksByStatus as $key => $tasks)
                <div class="card card-list">
                    <div class="card-title teal lighten-1 white-text">{{ $key }}</div>
                    <div class="card-content dropzone" data-title="{{ $key }}">
                        @foreach($tasks as $task)
                            <div class="card card-task" draggable="true" data-id="{{ $task->id }}">
                                <div class="card-content">
                                    <p>{{ $task->name }}</p>
                                </div>
                                <div class="card-action teal lighten-5 d-flex justify-content-between align-items-center">
                                    <span class="">12/{{ $task->id }} -
                                        @if($task->user)
                                            {{ $task->user()->value('name') }}
                                        @else
                                            Nobody
                                        @endif
                                    </span>
                                    <a role="button" class="activator mr-0 teal-text">
                                        <i class="material-icons tiny">settings</i>
                                    </a>
                                </div>
                                <!-- TODO: redo a dropdown -->
                                <div class="card-reveal p-0">
                                    <button class="card-title waves-effect waves-light btn-small teal lighten-5 mb-0 w-100"><i class="material-icons tiny teal-text">arrow_drop_down</i></button>
                                    <div class="collection m-0">
                                        <a href="#!" class="collection-item">Log activity</a>
                                        <a href="{{ route('projects.sprints.tasks.edit', [$project, $sprint, 144]) }}" class="collection-item">Edit</a>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/scrumboard.js') }}" defer></script>
@endpush